version: '3'

services:
  user_db:
    container_name: user_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ecommerce_user_db
      POSTGRES_PASSWORD: 12345678!
      POSTGRES_DB: ecommerce_user_db
    ports:
      - 5435:5432
    volumes:
      - ./ecommerce_user_db:/var/lib/postgresql/data
    networks:
      - ecommerce_network  
  
    
  address_db:
    container_name: address_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: address_db
      POSTGRES_PASSWORD: 12345678!
      POSTGRES_DB: address_db
    ports:
      - 5436:5432
    volumes:
      - ./address_db:/var/lib/postgresql/data
    
    networks:
      - ecommerce_network  

    search_history_db:
      container_name: search_history_db
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_USER: search_history_db
        POSTGRES_PASSWORD: 12345678!
        POSTGRES_DB: search_history_db
      ports:
        - 5437:5432
      volumes:
        - ./search_history_db:/var/lib/postgresql/data
      networks:
        - ecommerce_network 
    
    recommendation_db:
      container_name: recommendation_db
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_USER: recommendation_db
        POSTGRES_PASSWORD: 12345678!
        POSTGRES_DB: recommendation_db
      ports:
        - 5437:5432
      volumes:
        - ./recommendation_db:/var/lib/postgresql/data
      networks:
        - ecommerce_network 

  order_history_db:
    container_name: order_history_db
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: order_history_db
      MONGO_INITDB_ROOT_PASSWORD: 12345678!
    ports:
      - 27017:27017
    volumes:
      - ./order_history_db:/data/db
    
    networks:
      - ecommerce_network 


  order_db:
    container_name: order_db
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: order_db
      MONGO_INITDB_ROOT_PASSWORD: 12345678!
    ports:
      - 27018:27017
    volumes:
      - ./order_db:/data/db
    
    networks:
      - ecommerce_network

  cart_db:
    container_name: cart_db
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: cart_db
      MONGO_INITDB_ROOT_PASSWORD: 12345678!
    ports:
      - 27019:27017
    volumes:
      - ./cart_db:/data/db
    
    networks:
      - ecommerce_network


  review_db:
    container_name: review_db
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./review_db:/data/db

    command: redis-server --requirepass review_db!

    networks:
      - ecommerce_network


  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - user_db
      - address_db
      - product_db
      - review_db
      - search_history_db
    networks:
      - ecommerce_network
  

  user_crud:
    container_name: user_crud
    build: <>
    restart: always
    ports:
      - 8001:8001
    depends_on:
      - user_db
    networks:
      - ecommerce_network
  
  user_auth:
    container_name: user_auth
    build: <>
    restart: always
    ports:
      - 8002:8002
    depends_on:
      - user_db
    networks:
      - ecommerce_network
  
  recommendation:
    container_name: recommendation
    build: <>
    restart: always
    ports:
      - 8003:8003
    depends_on:
      - recommendation_db
    networks:
      - ecommerce_network
  
  search_service:
    container_name: search_service
    build: <>
    restart: always
    ports:
      - 8004:8004
    depends_on:
      - search_history_db
    networks:
      - ecommerce_network
  
  cart_service:
    container_name: cart_service
    build: <>
    restart: always
    ports:
      - 8005:8005
    depends_on:
      - cart_db
    networks:
      - ecommerce_network
  
  order_service:
    container_name: order_service
    build: <>
    restart: always
    ports:
      - 8006:8006
    depends_on:
      - order_db
      - order_history_db
    networks:
      - ecommerce_network
  

  #elastic search to find products
  #queue to search service comunicate with search history db
  #cache for product reviews
  #cache for order db

networks:
  ecommerce_network:
    driver: bridge
