@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

###
GET {{host}}/api/v1/health-check
Content-Type: {{contentType}}


###
POST {{host}}/api/v1/create/user
Content-Type: {{contentType}}

{
  "user_name": "joserafael",
  "password": "Rafa040500!",
  "first_name": "jose",
  "last_name": "hermoso",
  "email": "dadoschatos@gmail.com"
}

###
GET {{host}}/api/v1/get/user?email=teste@teste
Content-Type: {{contentType}}
Authorization: Bearer xxx




###
PUT {{host}}/api/v1/update/user?id=pbfbwuqk2dx0brpny92c4ink
Content-Type: {{contentType}}

{
  "user_name": "teste123",
  "password": "teste123",
  "first_name": "teste123",
  "last_name": "teste123",
  "email": "1",
  "last_login": "2019-01-01T00:00:00Z"
}